---
title: Criando um bot do telegram no R
author: 'Guilherme '
date: '2019-03-12'
categories:
  - R
tags:
  - bot
slug: criando-um-bot-do-telegram-no-r
---

# Introdução

Cada vez mais os bots estão sendo aplicados a múltiplas situações para auxiliar na automatização de procedimentos repetitivos.

Mas o que é um bot? Bot é o diminutivo de "robot", em português, robô. De acordo com a [Wikpédia](https://pt.wikipedia.org/wiki/Bot): é uma aplicação de software concebido para simular ações humanas repetidas vezes de maneira padrão, da mesma forma como faria um robô. No contexto dos programas de computador, pode ser um utilitário que desempenha tarefas rotineiras ou, num jogo de computador, um adversário com recurso a inteligência artificial.

A motivação desta postagem criar um bot a partir do R onde o bot responderia determinadas perguntas sobre algum conceito específico.

# Como criar um bot

Primeiramente vamos criar um projeto no RStudio, abra um novo script e carregue o pacote "telegram", caso não tenha ainda instale-o.

```{r eval=FALSE, tidy=FALSE}
install.packages("telegram")
library(telegram)
```

Agora precisamos criar um bot do Telegram e integrar ao R que será o controlador das ações deste bot.

Para criar o bot abra seu Telegram e busque pelo contato: @BotFather, é como estar conversando com uma pessoa real. Neste [link](https://core.telegram.org/bots#6-botfather) você poderá ver com detalhes como conversar com o "BotFather".


